### ISSUE TITLE
Not working while "Automatically Hide Menu Bar" is on in Big Sur

### ISSUE THREAD

**Issue by daysonhw** [pqrs-org/ShowyEdge#21]
That's all 

Thank you

**Comment by tekezo** [comment]
Thank you for feedback!

I fixed this issue at the latest beta version. (v4.0.1)
You can check it "Check for beta updates" button.
https://showyedge.pqrs.org/docs/help/use-beta/

Note:
These following options do not work when the menu bar is hidden due to the limitation of macOS.

<img width="640" alt="Screen Shot 2020-10-30 at 9 48 44" src="https://user-images.githubusercontent.com/659178/97647337-57c66080-1a95-11eb-86db-aef9a91db947.png">
